language: python
python: "3.9"
os: linux
dist: focal

before_install:
  - easy_install distribute

install:
  - pip install -r docs/requirements.txt

before_script:
  - git clean -f -d -x

script:
  - mkdocs build

deploy:
  provider: pages
  local_dir: site
  keep_history: true
  cleanup: true
  token: $GH_TOKEN
  on:
    branch: main