language: python
python: "3.9"
dist: focal

before_install:
  - easy_install distribute

install:
  - pip install -r docs/requirements.txt


before_script:
  - git clean -f -d -x

script:
  - mkdocs build


deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/.travis/deploy.sh
    on:
      branch: main