language: python
python: "3.9"
os: linux
dist: focal

before_install:
  - easy_install distribute

install:
  - pip install -r docs/requirements.txt

script:
  - mkdocs build

deploy:
  strategy: git
  provider: pages
  local_dir: site
  keep_history: true
  cleanup: false
  token: $GH_TOKEN
  edge: true
  on:
    branch: main