language: python
python: "3.9"
dist: focal

before_install:
  - easy_install distribute

install:
  - pip install -r docs/requirements.txt


before_script:
  - git clean -f -d -x

script:
  - mkdocs build


deploy:
  provider: pages
  local-dir: site
  skip-cleanup: true
  keep-history: true
  github-token: $GH_TOKEN
  on:
    branch: main